### ISSUE TITLE
Splitting into a library

### ISSUE THREAD

**Issue by TheAngryByrd** [eiriktsarpalis/nosln#1]
This is really cool tool!  

I think it would be nice to split the main logic into a library of it's own so something like FAKE can call it without having to shell out to the clitool.  

If that sounds good, I can do some work on the splitting and send a PR.

**Comment by eiriktsarpalis** [comment]
The tool is actually derived from this project: https://github.com/eiriktsarpalis/snippets/tree/master/SlnTools

Not really a library, but can be used in precisely the same way in FAKE scripts

**Comment by TheAngryByrd** [comment]
Oh perfect!
